[greeter]
background=/usr/share/backgrounds/zanx/login-background.png
theme-name=ZanX
icon-theme-name=ZanX
font-name=DejaVu Sans 10
clock-format=%H:%M
show-indicators=~host;~spacer;~clock;~session;~a11y;~power
